name             'mo_server_security'
maintainer       'Christian A. Rodriguez & Leandro Di Tommaso'
maintainer_email 'chrodriguez@gmail.com leandro.ditommaso@mikroways.net'
license          'MIT'
description      'Installs/Configures mo_server_security'
long_description 'Installs/Configures mo_server_security'
version          '0.1.6'

depends 'apt', '~>2.6.0'
depends 'simple_iptables', '~>0.7.0'
depends 'openssh', '~>1.3.4'
